language: 
  - ruby
  
rvm:
  - 2.3.1

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - gem install bundler
  - bundle exec rubocop --format emacs --out tmp/rubocop.txt || true
  - bundle exec brakeman -o tmp/brakeman.json
  - bundle exec brakeman_translate_checkstyle_format translate --file="tmp/brakeman.json" > tmp/brakeman_checkstyle.xml

  - export CI_REPORTS=$PWD/spec/reports
  - COVERAGE=true bundle exec rake ci:setup:rspec spec
  
after_script:
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | sudo tar -zxvf- -C /usr/local/bin
  - testspace publish @.testspace $TESTSPACE_TOKEN/${TRAVIS_BRANCH}#travis.Build.${TRAVIS_BUILD_NUMBER}
