language: 
  - ruby
  
rvm:
  - 2.3.1

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

before_script:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url samples.testspace.com
  
script:
  - gem install bundler
  - bundle exec rubocop --format emacs --out tmp/rubocop.txt || true
  - bundle exec brakeman -o tmp/brakeman.json
  - bundle exec brakeman_translate_checkstyle_format translate --file="tmp/brakeman.json" > tmp/brakeman_checkstyle.xml
  - COVERAGE=true bundle exec rake ci:setup:rspec spec
  
after_script:  
  - CI_REPORTS=$PWD/spec/reports testspace @.testspace.txt