dist: bionic

language:
  - ruby
rvm:
  - 2.3

services:
  - xvfb
addons:
  firefox: "78.0"

before_script:
  - curl -fsSL https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz | sudo tar -zxvf- -C /usr/local/bin
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url samples.testspace.com

script:
  - bundle exec rubocop --format emacs --out tmp/rubocop.txt || true
  - bundle exec brakeman -o tmp/brakeman.json
  - bundle exec brakeman_translate_checkstyle_format translate --file="tmp/brakeman.json" > tmp/brakeman_checkstyle.xml
  - COVERAGE=true bundle exec rake ci:setup:rspec spec

after_script:
  - CI_REPORTS=$PWD/spec/reports testspace @.testspace.txt
