name: Build
on:
  push:
  schedule:
    - cron:  '0 1 * * 0'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.3'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: samples
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install
        run: |
          bundle install --deployment --retry=3 --jobs=4
          RAILS_ENV=test bundle exec rake db:migrate
      - name: Analyze
        run: |
          bundle exec rubocop --format emacs --out tmp/rubocop.txt || true
          bundle exec brakeman -o tmp/brakeman.json
          bundle exec brakeman_translate_checkstyle_format translate --file="tmp/brakeman.json" > tmp/brakeman_checkstyle.xml
      - name: Test
        env:
          CI_NAME: github
          CI_BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
          CI_JOB_ID: ${{ env.GITHUB_RUN_ID }}
          CI_BUILD_URL: "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}"
          CI_BRANCH: ${{ env.GITHUB_REF }}
          #CI_PULL_REQUEST: ${{ env.GITHUB_RUN_ID }}
        run: |
          CI_REPORTS=spec/reports RAILS_ENV=test COVERAGE=true xvfb-run --server-args="-screen 0 1024x768x24" bundle exec rake ci:setup:rspec spec
      - name: Push
        run: |
          testspace @.testspace.txt --link=coveralls
        if: always()
